[package]
name = "tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
command = "0.0.0"
config = "0.13.2"
rand = "0.8.5"
serde = "1.0.144"
serde_derive = "1.0.144"
trees = "0.4.2"
